CREATE TABLE Merkmal (
  ID           int(10) NOT NULL AUTO_INCREMENT, 
  Bezeichnung  varchar(255) NOT NULL, 
  Beschreibung varchar(255),
  Datentyp 	varchar(255),
  PRIMARY KEY (ID));
  
CREATE TABLE Merkmalsausprägung (
  ID         int(10) NOT NULL AUTO_INCREMENT, 
  MerkmalID  int(10) NOT NULL, 
  Ausprägung varchar(255) NOT NULL, 
  PRIMARY KEY (ID));
  
CREATE TABLE SNR (
  ID 	int(10) NOT NULL AUTO_INCREMENT,
  SNR 	char(18) NULL,
  FA	char(20) NULL,
  TEIL	char(1) NULL,
  LINIE char(1) NULL,
  PRIMARY KEY (ID));

CREATE TABLE Rückmeldung (
  ID 		int(10) NOT NULL AUTO_INCREMENT,
  SNR		char(18) NULL,
  LINIE 	char(1) NULL,
  SNR_ID 	int(10) NULL,
  PRIMARY KEY (ID));
  
CREATE TABLE FA (
  FA	char(20) NOT NULL,
  PRIMARY KEY (FA));
  
CREATE TABLE TEIL (
  TEIL	char(1) NOT NULL,
  PRIMARY KEY (TEIL));

CREATE TABLE LINIE (
  LINIE	char(1) NOT NULL,
  PRIMARY KEY (LINIE));
  
CREATE TABLE Objekt2Merkmal (
  ID        int(10) NOT NULL AUTO_INCREMENT, 
  MerkmalID int(10) NOT NULL, 
  ObjektID  int(10) NOT NULL, 
  ObjektTyp int(10) NOT NULL, 
  PRIMARY KEY (ID));
  
CREATE TABLE Objekt2Merkmalsausprägung (
  ID                   int(10) NOT NULL AUTO_INCREMENT, 
  MerkmalsausprägungID int(10) NOT NULL, 
  ObjektID             int(10) NOT NULL, 
  ObjektTyp            int(10) NOT NULL, 
  PRIMARY KEY (ID));
  
CREATE TABLE ObjektTyp (
  ID			int(10) NOT NULL auto_increment,
  Bezeichnung	char(255) NOT NULL,
  Beschreibung 	char(255),
  PRIMARY KEY (ID));
  
ALTER TABLE Objekt2Merkmal ADD CONSTRAINT FKObjekt2Mer_Merk FOREIGN KEY (MerkmalID) REFERENCES Merkmal (ID);
ALTER TABLE Objekt2Merkmal ADD CONSTRAINT FKObjekt2Mer_ObjektTyp FOREIGN KEY (ObjektTyp) REFERENCES ObjektTyp(ID);


ALTER TABLE Objekt2Merkmalsausprägung ADD CONSTRAINT FKObjekt2MerkP_MerkP FOREIGN KEY (MerkmalsausprägungID) REFERENCES Merkmalsausprägung (ID);
ALTER TABLE Objekt2Merkmalsausprägung ADD CONSTRAINT FKObjekt2MerkP_ObjektTyp FOREIGN KEY (ObjektTyp) REFERENCES ObjektTyp(ID);


ALTER TABLE Merkmalsausprägung ADD CONSTRAINT FKMerkP_Merk FOREIGN KEY (MerkmalID) REFERENCES Merkmal (ID);


ALTER TABLE SNR ADD CONSTRAINT FKSNR_TEIL FOREIGN KEY (TEIL) REFERENCES TEIL (TEIL);
ALTER TABLE SNR ADD CONSTRAINT FKSNR_FA FOREIGN KEY (FA) REFERENCES FA (FA);
ALTER TABLE SNR ADD CONSTRAINT FKSNR_LINIE FOREIGN KEY (LINIE) REFERENCES LINIE (LINIE);


ALTER TABLE Rückmeldung ADD CONSTRAINT FKRück_SNR FOREIGN KEY (SNR_ID) REFERENCES SNR (ID);
ALTER TABLE Rückmeldung ADD CONSTRAINT FKRück_LINIE FOREIGN KEY (LINIE) REFERENCES LINIE (LINIE);


CREATE INDEX INDEX_TBL_SNR ON SNR (SNR);
CREATE INDEX INDEX_TBL_SNR2 ON SNR (TEIL);

CREATE INDEX INDEX_TBL_MerkP ON Merkmalsausprägung (MerkmalID, Ausprägung);
CREATE INDEX INDEX_TBL_MerkP2 ON Merkmalsausprägung (MerkmalID);

CREATE INDEX INDEX_TBL_O2MerkP ON Objekt2Merkmalsausprägung (ObjektID, ObjektTyp);

CREATE INDEX INDEX_TBL_O2Merk ON Objekt2Merkmal (ObjektID, ObjektTyp);

CREATE INDEX INDEX_TBL_Rück ON Rückmeldung (SNR);





























# ALTER TABLE Objekt2Merkmal ADD CONSTRAINT  FOREIGN KEY () REFERENCES LINIE ();
# ALTER TABLE Objekt2Merkmal ADD CONSTRAINT  FOREIGN KEY () REFERENCES TEIL ();
# ALTER TABLE Objekt2Merkmal ADD CONSTRAINT  FOREIGN KEY () REFERENCES FA ();
# ALTER TABLE Objekt2Merkmal ADD CONSTRAINT  FKObjekt2Mer_SNR FOREIGN KEY (ObjektID) REFERENCES SNR (ID);
# ALTER TABLE Objekt2Merkmal ADD CONSTRAINT  FOREIGN KEY () REFERENCES Rückmeldung ();

# ALTER TABLE Objekt2Merkmalsausprägung ADD CONSTRAINT  FOREIGN KEY () REFERENCES Rückmeldung ();
# ALTER TABLE Objekt2Merkmalsausprägung ADD CONSTRAINT  FKObjekt2MerkP_SNR FOREIGN KEY (ObjektID) REFERENCES SNR (ID);
# ALTER TABLE Objekt2Merkmalsausprägung ADD CONSTRAINT  FOREIGN KEY () REFERENCES FA ();
# ALTER TABLE Objekt2Merkmalsausprägung ADD CONSTRAINT  FOREIGN KEY () REFERENCES TEIL ();
# ALTER TABLE Objekt2Merkmalsausprägung ADD CONSTRAINT  FOREIGN KEY () REFERENCES LINIE ();
