= Einführung in Datenbankstruktur
:toc:
:toc-title: Inhaltsverzeichnis
ifndef::main-file[]
:imagesdir: bilder
endif::main-file[]
ifdef::main-file[]
:imagesdir: prop-db/bilder
endif::main-file[]



== Datenbankvorstellung

Die proprietäre Datenstruktur basiert auf einem relationalem Datenmodell, welches als Standard in der Datenbankentwicklung genutzt wird. Zu Grunde liegt diesem vier Elemente: Tabellen, Attribute, Beziehungen und die Grundlage der relationalen Algebra. Diese ist auch die Grundlage für die Datenbanksprache SQL. +
Das Relationale Datenbankenmodell besteht aus einer Ansammlung von Tabellen, die durch Beziehungen mit einander verknüpft sind. In jeder Tabelle werden die Datensätze als Tupel (Zeilen) gespeichert. Jedes Tupel besteht aus mehreren Attributen, welche als Spalten in einer Tabelle bekannt sind.    

.Code 1 - Beispiel für die Erstellung einer Tabelle
[source, sql]
----
CREATE TABLE `Test1` (
    `id` int NOT NULL AUTO_INCREMENT,
    `vorname` varchar(255) NOT NULL,
    `nachname` varchar(255) NOT NULL,
    PRIMARY KEY (´id´)
)
----

Unter der proprietären Datenstruktur versteht man ein herstellerspezifisches Modell, welches zur Verwaltung von nutzerspezifischen Daten entwickelt und dessen Weiterentwicklung eingeschränkt wird. Um dies zu realisieren wird die Data Definition Language (DDL) verwendet. Sie macht eine herstellerspezifische Entwicklung möglich, allerdings schließt diese gleichzeitig eine aufwendige Weiterentwicklung mit ein. 

.Code 2 - Beispiel für die Weiterentwicklung
[source, sql]
----
ALTER TABLE `Test1`
ADD COLUMN `alter` int,
DEFAULT NULL;
----

Der Vorteil der proprietären Datenstruktur besteht in einer spezifischen Entwicklung eines Datenmodelles, welche einen geringen Entwicklungsaufwand bedarf. Dies belegt der Codebeispiel 1, währenddessen erkennt man im Codebeispiel 2, dass eine Weiterentwicklung der Datenstruktur viele Systemtest mit sich zieht und damit viel Zeil kostet.
