= Implementierung
:toc:
:toc-title: Inhaltsverzeichnis
ifndef::main-file[]
:imagesdir: bilder
endif::main-file[]
ifdef::main-file[]
:imagesdir: document-oriented/bilder
endif::main-file[]

== Systemvoraussetzungen

Alle Implementierungen wurden unter den folgenden Voraussetzungen vorgenommen:

* Windows 10 Home 64-bit
* Intel Core i7-1065G7
* 16 GB RAM

== Datenbank
=== Allgemein

Über ein relationales Datenbankmanagementsystem (RDBMS) kann die proprietäre Datenstruktur realisiert werden. Es wurde über XAMPP, einem kostenlosen Programmpaket von freier Software, welche meiste für ein Apache Webserver verwendet wird, ein MySQL Server 8.0 installiert und konfiguriert. +
Um das relationale Datenmodell einfach zu realisieren, wurde zusätzlich HeidiSQL installiert, einem freien Client für das Datenbanksystem MySQL. Es wird hierbei die Structured Query Language (SQL) genutzt. +
 +
Um dies zu verdeutlichen folgen Quelltextbeispiele. Diese zeigen wie eine Tabelle angelegt, Daten eingetragen, sowie Fremdschlüsselbeziehung erstellt werden.  

.Code 3 - Anlegen der Tabelle Database
[source, sql]
----
CREATE TABLE `Database` 
(
  baseID    int NOT NULL AUTO_INCREMENT,
  SNR 	    varchar(18) NOT NULL,
  FA	    varchar(12),
  TEIL	    varchar(12),
  LINIE     varchar(12),
  Fehler    varchar(12),
  Begintime datetime,
  Endtime   datetime,
  PRIMARY KEY (baseID)
);
----

.Code 4 - Daten in Database eintragen
[source, sql]
----
INSERT INTO `Database` (`SNR`,`FA`,`TEIL`,`LINIE`,`Fehler`,`Begintime`,`Endtime`)
    VALUES ('1923219423129', '009606', 'A', '1', '0', '2018-01-02T05:47:45', '2018-01-02T05:48:45');
----

.Code 5 - Fremdschlüsselbeziehung anlegen
[source, sql]
----
ALTER TABLE `Database` ADD CONSTRAINT FKDatabase FOREIGN KEY (`baseID`) REFERENCES `Input` (`baseID`);
----

Um gezielte Abfragen zu tätigen, die später für die Analyse benötigt werden, bedarf es ein SELECT-STATEMENT mit einer WHERE-CLAUSEL. Dadurch wird eine gute Performance gesichert.

.Code 6 - SELECT-Statement inkl. WHERE-Clausel
[source, sql]
----
SELECT * FROM `Database` WHERE `baseID` = `2`
----

== Anwendungen
=== Programmiersprache

Die Implementierung der Anwendungen wurde mit der Programmiersprache Python vorgenommen. Als Entwicklungsumgebung, innerhalb des Projektes, wurde Notepad ++ genutzt.  Für die Implementierung wurde die Python-Version 3.7.3 genutzt. +
Die Ausführung des Python-Programmes wurde über die Kommandozentrale (CMD), von Windows 10, vorgenommen. +
Dies wird in im Codebeispiel 7 verdeutlicht. 

.Code 7 - Ausführung des Python-Programmes über CMD
[source, sh]
----
>python analyse.py 
----

=== Kommunikation zwischen Anwendung und Datenbank

Durch die Python-Bibliothek mysql-connector-python wurde eine Verbindung zwischen Anwendung und MySQL-Datenbankserver hergestellt. +
Dies kann man über die Kommandozentrale installieren, wie im Codebeispiel 8 beschrieben.

.Code 7 - Installation Python-Bibliothek über CMD
[source, sh]
----
>pip install mysql-connector-python
----

Die installierte Bibliothek wird nun in die Anwendung eingebunden, um eine Verbindung zur Datenbank herstellen zu können. Dazu müssen folgende Parameter gesetzt werden um einen Zugriff zu erhalten: host, database, user und password.

.Code 8 - Herstellung der Verbindung zwischen Anwender und Datenbank
[source, python]
----
import mysql.connector

connection = mysql.connector.connect(host = "127.0.0.1", user = "root", password = "1234", database = "test")
----

Nach dem Aufbau der Verbindung zur Datenbank, wird ein Cursor gesetzt. Diesem wird per Cursor-Funktion execute eine SELECT-Abfrage übergeben. Zusätzlich dazu bietet der Cursor Varianten an, um die Ergebnismenge bereitzustellen. Zum Beispiel:

* _fetchall()_, welcher die gesamte Ergebnismenge wieder gibt
* _fetchone()_, welcher nur die erste Zeile der Ergebnismenge wieder gibt

.Code 9 - Erstellung eines Cursor's sowie einer SELECT-Abfrage
[source, python]
----
cursor = connection.cursor()
cursor.execute("SELECT * FROM `Database`")
result = cursor.fetchall()
----

Um die execute auszuführen, bedarf es ein Commit, welches die Anweisung ausführt.  Nach dem Ausführen, wird der Cursor, sowie die Connection per close() Funktion geschlossen.

.Code 10 - Commit und Close der Connection
[source, python]
----
connection.commit()

connection.close()
cursor.close()
----

== Implementierung der Struktur
== Implementierung der Datenloader
== Implementierung der Analysen

[source, python]
----
@app.route('/')
def home():
    return render_template("inline.html")
----

== Evolution des Datenmodells

