= Zusammenfassung und Ausblick
:toc:
:toc-title: Inhaltsverzeichnis
:imagesdir: bilder


== Lessons Learned

Die wichtigste Entscheidung ist welche Datenzusammenhänge wie gespeichert werden. Wenn diese Zusammenhänge durch die Datenbankstruktur vorgegeben werden sind Abfragen einfach und performant. Wenn diese Beziehungen aber nicht gespeichert werden, dann müssen diese Informationen durch die Abfragen wiederhergestellt werden. So sind Abfragen in der proprietären Struktur mit einfachen SQL-Abfragen möglich, während bei der universellen Struktur Abfrageergebnisse zum Teil zwischengespeichert werden müssen, um die richtige Analyse zu ermöglichen. Das sollte man berücksichtigen, im Besonderen, da Analysen besonders wertvoll sind, wenn diese durch Mitarbeiter der Fachdomäne erstellt werden können. Mit der Datenstruktur ist natürlich die Abfragestruktur eng verbunden, auch hier hat man eine Wahl Möglichkeit. Man kann entweder große komplexe Abfragen nutzen oder mehrere kleine. Damit kann die Logik der Abfragen zwischen Datenbankserver und Client verschoben werden. Die Datenbank nahe Lösung ist meist performanter, aber auch schwerer verständlich oder auch nicht ohne weiteres realisierbar.

Weiterhin hat gerade die universell relationale Struktur gezeigt, dass Laufzeit und Speicher sich gegenseitig ersetzten können. So hat das Setzen von Indices die Performance erhöht, aber auch die Datenbank um einiges vergrößert.

== Fazit
Das Projekt hat gezeigt, dass es bei der Datenbank und Datenmodellauswahl wie bei den meisten Architekturentscheidungen keine allgemeingültige Antwort auf die Frage "Was ist die beste Lösung?" gibt. Dafür ist die Variabilität der Anforderungen zwischen den verschiedenen Anwendungsgebieten zu hoch. Man muss somit von Projekt zu Projekt unterscheiden, was die am besten umsetzbare Lösung ist. In realen Projekten kommen natürlich auch neben technischen Anforderungen, einschränkende Faktoren wie Kosten, bestehende Datenbankserver und Fähigkeiten des Entwicklerteams hinzu.

